### ISSUE TITLE
Implement clouds moving when game not paused

### ISSUE THREAD

**Issue by w1158mxs** [WSUCEG-7140/Tempus_Fugit_Minecraft#21]
on stable speed, clouds must move when the game is not paused.

**Comment by bakursait2** [comment]
This issue is duplicated with [issue#4](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/4).
I will close this [issue#21](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/21) and work on [issue#4](https://github.com/WSUCEG-7140/Tempus_Fugit_Minecraft/issues/4).
