### ISSUE TITLE
Stop the user from crossing the borders of the game world.

### ISSUE THREAD

**Issue by xieWright** [WSUCEG-7140/Tempus_Fugit_Minecraft#25]
When a user go to the end of the world, the user won't be allowed to jump from or dig through the border blocks.

**Comment by w1158mxs** [comment]
I recommend making it more specific 
some ideas:
Do you want to make the wall longer
or
make a virtual wall
or
create a limit on users' moves?

**Comment by bakursait2** [comment]
You are right. I meant a virtual block where the player can not go beyond the walls.
A player might go up as far as they want but not crossing the borders.

I will adjust that.
Thanks
