### ISSUE TITLE
Player cannot add blocks to the clouds

### ISSUE THREAD

**Issue by bakursait2** [WSUCEG-7140/Tempus_Fugit_Minecraft#42]
As A Minecraft developer, I want to prevent user from attaching blocks to clouds, so the clouds can not be adjusted.

**Comment by w1158mxs** [comment]
I like to build my house in the clouds! however, I'm looking to keep the user adding some light and dark clouds to existed clouds, make sure this will not make a conflict, number 4 will build light cloud, 5 will build dark cloud

**Comment by bakursait2** [comment]
well, I can make this in another issue.
